In [1]:
from early_exit import EarlyExitNetwork,train_model,test_all_exits_accuracy


In [2]:
from copy import deepcopy
import torch.nn as nn
class SplitModel(nn.Module):
    def __init__(self,pretrained_model):
        super(SplitModel, self).__init__() 
        self.device_side_net = deepcopy(pretrained_model.features[:14])
        self.server_side_net = deepcopy(pretrained_model.features[14:27])
        
        self.cloud_net = nn.Sequential(
            deepcopy(pretrained_model.features[27:]),
            nn.Flatten(),
            deepcopy(pretrained_model.classifier)
        )
        self.net = nn.Sequential(
            self.device_side_net,
            self.server_side_net,
            self.cloud_net
        )
        
    def forward(self, x):
        x = self.net(x)
        return x

In [3]:
class ExitLayers(nn.Module):
    def __init__(self, layers,classes=10):
        super(ExitLayers, self).__init__()
        self.layers = [nn.Flatten()]
        for i in range(len(layers)-1):
            self.layers.append(nn.Linear(layers[i],layers[i+1]))
        
        self.layers.append(nn.Linear(layers[-1],classes))
        self.layers.append(nn.Softmax(dim=1))
        self.network = nn.Sequential(*self.layers)
    def forward(self, x):
        return self.network(x)


In [4]:
import torch
x = torch.randn(1,3,32,32)
model = torch.hub.load("chenyaofo/pytorch-cifar-models", "cifar10_vgg19_bn", pretrained=True)
thresholds = [0.9,0.9]
seperated_model = SplitModel(model)


exit_0 =seperated_model.device_side_net(x)
exit_0_shape = seperated_model.device_side_net(x).flatten().shape
print(exit_0_shape)

exit_1 = seperated_model.server_side_net(exit_0)
exit_1_shape = seperated_model.server_side_net(exit_0).flatten().shape
print(exit_1_shape)

Using cache found in C:\Users\paral/.cache\torch\hub\chenyaofo_pytorch-cifar-models_master


torch.Size([8192])
torch.Size([4096])


In [5]:
neurons_in_exit_0 = [exit_0_shape[0],1024,1024]
neurons_in_exit_1 = [exit_1_shape[0],1024,1024]

exits =nn.ModuleList([ExitLayers(neurons_in_exit_0),ExitLayers(neurons_in_exit_1)])

In [6]:
eenet = EarlyExitNetwork(seperated_model.net,exits,thresholds)

In [7]:
import torchvision
from torchvision import  transforms
import torch
transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])

batch_size = 2

testset = torchvision.datasets.CIFAR10(root='data', train=False,
                                       download=True, transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=batch_size,
                                         shuffle=False, num_workers=2)



Files already downloaded and verified


In [59]:
import torch
def train_whole_network(model,loader,criterion,optimizer,device=None):
    def create_onehot_repeated_tensor(labels_batch, n_classes, repeats):
        # Get batch size from labels
        batch_size = labels_batch.shape[0]
        
        # Create empty tensor to store results
        result = torch.zeros(batch_size, repeats, n_classes, dtype=torch.float)
        
        # For each item in the batch
        for i in range(batch_size):
            # Create one-hot encoding
            one_hot = torch.zeros(n_classes, dtype=torch.float)
            one_hot[labels_batch[i]] = 1  # Remove the [0] indexing since labels are 1D
            
            # Repeat for specified number of times
            result[i] = one_hot.unsqueeze(0).repeat(repeats, 1)
        
        return result
    if device is None:
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    for img,labels in loader:
        img = img.to(device)
        labels = labels.to(device)
        output = model(img)
        
        number_of_exits =output.shape[1]
        number_of_classes = output.shape[2]
        labels = create_onehot_repeated_tensor(labels,number_of_classes,number_of_exits)
      
        loss = criterion(output,labels)
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()
        
loss = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(eenet.parameters())
labels,output =train_whole_network(eenet,testloader,loss,optimizer)


torch.Size([2, 3, 10])
torch.Size([2, 3, 10])
tensor(0.8775, grad_fn=<DivBackward1>)


In [ ]:
from early_exit import train_whole_network,test_all_exits_accuracy


In [76]:
with torch.no_grad():     
        images,labels = next(iter(testloader))
        images  = images.to('cpu')
        outputs=  eenet(images)
        num_exits = outputs.shape[1]

In [85]:

for batch_number, batch_output in enumerate(outputs):
    for exit in range(num_exits):
        answer = torch.argmax(batch_output[exit],dim=0)
        if answer == labels[batch_number]:
            correct[exit] += 1
    total += 1
    
        
        

0
tensor([0.1022, 0.1012, 0.1012, 0.1007, 0.0979, 0.0982, 0.0992, 0.1059, 0.0971,
        0.0964])
1
tensor([0.0986, 0.1003, 0.1015, 0.1013, 0.1020, 0.0963, 0.0955, 0.1032, 0.1025,
        0.0987])
2
tensor([-0.5380, -1.9808, -0.6144,  6.4531, -0.8817,  0.1903, -0.3943, -0.3225,
        -1.7984, -0.1151])
Correct
0
tensor([0.1014, 0.0984, 0.1045, 0.1002, 0.0980, 0.0979, 0.0977, 0.1034, 0.0987,
        0.0998])
1
tensor([0.0980, 0.1023, 0.1033, 0.1001, 0.1022, 0.0964, 0.0968, 0.1012, 0.1015,
        0.0983])
2
tensor([ 2.3517,  1.3625, -1.2507, -2.1495, -2.6815,  0.2080, -0.6990, -1.6665,
         5.5055, -0.9822])
Correct
